<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../TheMovies/Models/Cinema.cs" Link="Models/Cinema.cs" />
    <Compile Include="../TheMovies/Models/CinemaRoom.cs" Link="Models/CinemaRoom.cs" />
    <Compile Include="../TheMovies/Models/Movie.cs" Link="Models/Movie.cs" />
    <Compile Include="../TheMovies/Models/Reservation.cs" Link="Models/Reservation.cs" />
    <Compile Include="../TheMovies/Models/Screening.cs" Link="Models/Screening.cs" />
    <Compile Include="../TheMovies/Repositories/FileReservationRepository.cs" Link="Repositories/FileReservationRepository.cs" />
    <Compile Include="../TheMovies/Repositories/FileScreeningRepository.cs" Link="Repositories/FileScreeningRepository.cs" />
    <Compile Include="../TheMovies/ViewModels/RelayCommand.cs" Link="ViewModels/RelayCommand.cs" />
    <Compile Include="../TheMovies/ViewModels/ReservationViewModel.cs" Link="ViewModels/ReservationViewModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
